use super::MuxmlNote2;
use crate::backend::errors::backend_error::BackendError;
pub fn get_fretboard_note2(string: char, fret: u8) -> Result<MuxmlNote2, BackendError<'static>> {
    Ok(MuxmlNote2 {
        step: STRING_BASE_NOTES[string as usize]
            .unwrap_or_else(|| panic!("Don't know base note for string {string}"))
            + fret,
        dead: false,
    })
}

/// TODO fill in everything with u8s for no extra cost and more flexibility
/// Generated by tools/gen_note_lookup.rs
#[rustfmt::skip]
const STRING_BASE_NOTES: [Option<u8>;256]= [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, Some(45), Some(59), None, Some(50), Some(40), None, Some(55), None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, Some(64), None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None];
